Update JS rules and linter
subvisual/guides pull request #27
Opened 2017-02-21 23:58 UTC by gabrielpoca

I believe that most of us agree that airbnb's eslint configuration
should be our default linter for JavaScript. I know that, for some
projects, we may feel that tweaking it would be better, but I believe
that we should agree in a set of rules and follow them. We'll never find
something that everyone likes at first. I also think that we need a
default configuration because it will remove this conversation out of
the way, and let us focus on different things. I also think that we need
consistency in our projects, and we need to remove the amount of
decisions we make whenever we start a new one. This doesn't mean that
this topic is closed forever, we should be open to new ideas, but keep
in mind that the benefits of using one styleguide or the other are
probably very small. Most times, I believe, it's a matter of taste.

2017-02-22 09:35 UTC, naps62 approved these changes

2017-02-22 09:35 UTC, naps62 commented on style/js/README.md
> +* Don't use CoffeScript
how about removing this section altogether?

2017-02-22 10:41 UTC, gabrielpoca commented on style/js/README.md
> +* Don't use CoffeScript
👍

2017-02-22 11:38 UTC, frmendes commented on linters/js/README.md
> +    npm i --save-dev eslint-config-airbnb
Should we support yarn or add yarn docs?

2017-02-22 11:50 UTC, gabrielpoca commented on linters/js/README.md
> +    npm i --save-dev eslint-config-airbnb
I think that conversations needs to happen, but not here. At the moment, some people are experimenting with `yarn`, but our default remains `npm`.

2017-02-22 11:57 UTC, frmendes commented on linters/js/README.md
> +    npm i --save-dev eslint-config-airbnb
👍 I'm fine with that.

2017-02-22 11:57 UTC, frm approved these changes

2017-02-22 12:21 UTC, joaojusto commented
Airbnb seems a very good starting point :shipit:

2017-02-23 11:49 UTC, gabrielpoca commented
@subvisual/developers last call for comments 🍾

2017-02-23 12:39 UTC, gabrielpoca commented
After discussing with Azevedo, I changed the configuration to override two of Airbnb's rules. The rules don't affect the styling; it just makes it a little less strict. You'll find an explanation in the README.

2017-02-23 13:12 UTC, azevedo requested changes

2017-02-23 13:12 UTC, azevedo-252 commented on linters/js/README.md
> +Airbnb's configuration is great, but some of their rules are to strict for our
"... `too` strict ..."

2017-02-23 14:16 UTC, gabrielpoca commented on linters/js/README.md
> +Airbnb's configuration is great, but some of their rules are to strict for our
👍

2017-02-23 15:23 UTC, azevedo approved these changes

2017-02-23 16:27 UTC, naps62 approved these changes

2017-02-23 21:01 UTC, pfac approved these changes

2017-02-27 03:23 UTC, ronaldofs approved these changes

2017-03-15 17:33 UTC, merged